export const MeasurementSchema = {
	name: "Measurements",
    primaryKey: "measurementId",
    properties: {
        measurementId: "string",
        userId: "string",
        age: "int?",
        weight: "float?",
        height: "float?",
        neck: "float?",
        shoulder: "float?",
        chest: "float?",
        abdomen: "float?",
        waist: "float?",
        hips: "float?",
        rightBicep: "float?",
        leftBicep: "float?",
        rightForearm: "float?",
        leftForearm: "float?",
        rightThigh: "float?",
        leftThigh: "float?",
        rightCalf: "float?",
        leftCalf: "float?",
        bodyFat: "float?",
    },
};