export const MeasurementSchema = {
	name: "Measurements",
    primaryKey: "measurementId",
    properties: {
        measurementId: "string",
        userId: "string",
        weight: "string?",
        height: "string?",
        age: "string?",
        chest: "string?",
        waist: "string?",
        hips: "string?",
        rightBicep: "string?",
        leftBicep: "string?",
        rightForearm: "string?",
        leftForearm: "string?",
        rightThigh: "string?",
        leftThigh: "string?",
        rightCalf: "string?",
        leftCalf: "string?",
        neck: "string?",
        shoulder: "string?",
        bodyFat: "string?",
        muscleMass: "string?",
        boneMass: "string?",
        waterPercentage: "string?",
        visceralFat: "string?",
        metabolicAge: "string?",
        createdAt: "date",
        updatedAt: "date",
        syncStatus: "string?",
    },
};