// Categories as a separate collection
export const exerciseCategories = [
	{ id: "Chest", name: "Chest" },
	{ id: "Back", name: "Back" },
	{ id: "Arms", name: "Arms" },
	{ id: "Legs", name: "Legs" },
	{ id: "Shoulders", name: "Shoulders" },
	{ id: "Core", name: "Core" },
	{ id: "Cardio", name: "Cardio" },
];

export const muscleTypes = [
	{ id: "Bicep", name: "Bicep" },
	{ id: "Tricep", name: "Tricep" },
	{ id: "Shoulder", name: "Shoulder" },
	{ id: "Forearm", name: "Forearm" },
	{ id: "Chest", name: "Chest" },
	{ id: "Abs", name: "Abs" },
	{ id: "Lats", name: "Lats" },
	{ id: "Traps", name: "Traps" },
	{ id: "Lower Back", name: "Lower Back" },
	{ id: "Quads", name: "Quads" },
	{ id: "Hamstrings", name: "Hamstrings" },
	{ id: "Calfs", name: "Calfs" },
];

// Equipment types for better filtering
export const equipmentTypes = [
	{ id: "Barbell", name: "Barbell" },
	{ id: "Dumbbell", name: "Dumbbell" },
	{ id: "Machine", name: "Machine" },
	{ id: "Cable", name: "Cable" },
	{ id: "Bodyweight", name: "Bodyweight" },
	{ id: "Cardio Equipment", name: "Cardio Equipment" },
	{ id: "Assisted", name: "Assisted" },
	{ id: "Other", name: "Other" },
];

// Exercise types that determine form layouts
export const exerciseTypes = [
	{ id: "bodyweight", name: "Bodyweight" },
	{ id: "weightlifting", name: "Weightlifting" },
	{ id: "assisted", name: "Assisted" },
	{ id: "cardio-distance", name: "Cardio (Distance)" },
	{ id: "cardio-time", name: "Cardio (Time)" },
];

// Exercises with more detailed information
export const exercises = [
	// Cardio exercises
	{
		id: "treadmill_run",
		name: "Treadmill Running",
		categoryId: "Cardio",
		equipment: ["Cardio Equipment"],
		primaryMuscles: ["Quadriceps", "Hamstrings", "Calves"],
		secondaryMuscles: ["Core", "Glutes"],
		difficulty: "scalable",
		type: "cardio-distance",
		instructions:
			"Start with a warm-up walk, then increase speed to a comfortable running pace. Maintain upright posture with natural arm swing.",
		videoUrl: "/videos/treadmill_run.mp4",
		imageUrl: "/images/treadmill_run.jpg",
	},
	{
		id: "stationary_bike",
		name: "Stationary Bike",
		categoryId: "Cardio",
		equipment: ["Cardio Equipment"],
		primaryMuscles: ["Quadriceps", "Hamstrings", "Calves"],
		secondaryMuscles: ["Glutes"],
		difficulty: "scalable",
		type: "cardio-distance",
		instructions:
			"Adjust the seat height so your knee is slightly bent at the bottom of the pedal stroke. Maintain a steady rhythm at your target resistance level.",
		videoUrl: "/videos/stationary_bike.mp4",
		imageUrl: "/images/stationary_bike.jpg",
	},
	{
		id: "elliptical",
		name: "Elliptical Trainer",
		categoryId: "Cardio",
		equipment: ["Cardio Equipment"],
		primaryMuscles: ["Quadriceps", "Hamstrings", "Glutes"],
		secondaryMuscles: ["Core", "Arms", "Shoulders"],
		difficulty: "scalable",
		type: "cardio-distance",
		instructions:
			"Stand upright with good posture on the machine, engage core muscles, and use both the leg and arm components for a full-body workout.",
		videoUrl: "/videos/elliptical.mp4",
		imageUrl: "/images/elliptical.jpg",
	},
	{
		id: "rowing_machine",
		name: "Rowing Machine",
		categoryId: "Cardio",
		equipment: ["Cardio Equipment"],
		primaryMuscles: ["Back", "Shoulders", "Quadriceps"],
		secondaryMuscles: ["Biceps", "Hamstrings", "Core"],
		difficulty: "scalable",
		type: "cardio-distance",
		instructions:
			"Sit with feet secured on the footrests, grab the handle with an overhand grip. Push with your legs, hinge at the hips, then pull the handle to your lower chest. Return in the reverse order.",
		videoUrl: "/videos/rowing_machine.mp4",
		imageUrl: "/images/rowing_machine.jpg",
	},
	{
		id: "stair_climber",
		name: "Stair Climber",
		categoryId: "Cardio",
		equipment: ["Cardio Equipment"],
		primaryMuscles: ["Quadriceps", "Glutes", "Calves"],
		secondaryMuscles: ["Hamstrings", "Core"],
		difficulty: "scalable",
		type: "cardio-time",
		instructions:
			"Stand upright on the machine with good posture, lightly hold the handrails for balance, and maintain a consistent stepping pace focusing on pushing through your heels.",
		videoUrl: "/videos/stair_climber.mp4",
		imageUrl: "/images/stair_climber.jpg",
	},
	{
		id: "jump_rope",
		name: "Jump Rope",
		categoryId: "Cardio",
		equipment: ["Other"],
		primaryMuscles: ["Calves", "Shoulders"],
		secondaryMuscles: ["Core", "Forearms", "Quadriceps"],
		difficulty: "intermediate",
		type: "cardio-time",
		instructions:
			"Hold the handles with a firm grip, keep elbows close to your sides, and use your wrists to turn the rope. Jump just high enough to clear the rope, landing softly on the balls of your feet.",
		videoUrl: "/videos/jump_rope.mp4",
		imageUrl: "/images/jump_rope.jpg",
	},

	// Assisted exercises
	{
		id: "assisted_pull_up",
		name: "Assisted Pull-Up",
		categoryId: "Back",
		equipment: ["Assisted", "Machine"],
		primaryMuscles: ["Back", "Lats"],
		secondaryMuscles: ["Biceps", "Shoulders"],
		difficulty: "beginner",
		type: "assisted-weight",
		instructions:
			"Adjust the assistance weight to your needs. Grip the bar with hands wider than shoulder-width, then pull yourself up until your chin is over the bar. Lower back down with control.",
		videoUrl: "/videos/assisted_pull_up.mp4",
		imageUrl: "/images/assisted_pull_up.jpg",
	},
	{
		id: "assisted_dip",
		name: "Assisted Dip",
		categoryId: "Chest",
		equipment: ["Assisted", "Machine"],
		primaryMuscles: ["Chest", "Triceps"],
		secondaryMuscles: ["Shoulders"],
		difficulty: "beginner",
		type: "assisted-weight",
		instructions:
			"Set the assistance weight. Grip the parallel bars, lower your body by bending your elbows until your upper arms are parallel to the ground, then push back up.",
		videoUrl: "/videos/assisted_dip.mp4",
		imageUrl: "/images/assisted_dip.jpg",
	},
	{
		id: "smith_machine_squat",
		name: "Smith Machine Squat",
		categoryId: "Legs",
		equipment: ["Assisted", "Machine"],
		primaryMuscles: ["Quadriceps", "Glutes"],
		secondaryMuscles: ["hamstrings", "calves", "core"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Position yourself under the bar with feet shoulder-width apart. Unrack the bar, lower into a squat position until thighs are parallel to the ground, then push back up.",
		videoUrl: "/videos/smith_machine_squat.mp4",
		imageUrl: "/images/smith_machine_squat.jpg",
	},
	{
		id: "smith_machine_bench_press",
		name: "Smith Machine Bench Press",
		categoryId: "Chest",
		equipment: ["Assisted", "Machine"],
		primaryMuscles: ["Chest"],
		secondaryMuscles: ["Triceps", "Shoulders"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Lie on a bench under the Smith machine bar. Position the bar above your chest, unrack it, then lower it to your mid-chest before pressing it back up to full extension.",
		videoUrl: "/videos/smith_machine_bench_press.mp4",
		imageUrl: "/images/smith_machine_bench_press.jpg",
	},
	{
		id: "cable_chest_press",
		name: "Cable Chest Press",
		categoryId: "Chest",
		equipment: ["Cable"],
		primaryMuscles: ["Chest"],
		secondaryMuscles: ["Triceps", "Shoulders"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand in the center of a cable machine with cables set at chest height. Grip the handles with palms facing down, step forward, and press the handles forward until arms are extended.",
		videoUrl: "/videos/cable_chest_press.mp4",
		imageUrl: "/images/cable_chest_press.jpg",
	},

	// Original strength exercises
	{
		id: "db_bench_press",
		name: "Dumbbell Bench Press",
		categoryId: "Chest",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Chest"],
		secondaryMuscles: ["triceps", "shoulders"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Lie on a bench with a dumbbell in each hand. Push the dumbbells up until your arms are fully extended, then lower them back to chest level.",
		videoUrl: "/videos/db_bench_press.mp4",
		imageUrl: "/images/db_bench_press.jpg",
	},
	{
		id: "bb_bench_press",
		name: "Barbell Bench Press",
		categoryId: "Chest",
		equipment: ["Barbell", "Bench"],
		primaryMuscles: ["Chest"],
		secondaryMuscles: ["triceps", "shoulders"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Lie on a bench with a barbell gripped slightly wider than shoulder width. Lower the bar to your chest, then push it back up to full arm extension.",
		videoUrl: "/videos/bb_bench_press.mp4",
		imageUrl: "/images/bb_bench_press.jpg",
	},
	{
		id: "db_row",
		name: "Dumbbell Row",
		categoryId: "Back",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Back"],
		secondaryMuscles: ["biceps", "shoulders"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Place one knee and hand on a bench, with the other foot on the floor. Hold a dumbbell in your free hand, pull it up to your hip, then lower it back down with control.",
		videoUrl: "/videos/db_row.mp4",
		imageUrl: "/images/db_row.jpg",
	},
	{
		id: "bb_deadlift",
		name: "Barbell Deadlift",
		categoryId: "Back",
		equipment: ["Barbell"],
		primaryMuscles: ["Back", "Hamstrings"],
		secondaryMuscles: ["glutes", "forearms", "core"],
		difficulty: "advanced",
		type: "weightlifting",
		instructions:
			"Stand with feet hip-width apart, bend at the hips and knees to grip the barbell. Keeping your back straight, stand up while holding the barbell, then lower it back to the ground with control.",
		videoUrl: "/videos/bb_deadlift.mp4",
		imageUrl: "/images/bb_deadlift.jpg",
	},
	{
		id: "db_curl",
		name: "Dumbbell Curl",
		categoryId: "Arms",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Biceps"],
		secondaryMuscles: ["forearms"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand holding dumbbells at your sides with palms facing forward. Curl the weights up toward your shoulders, then lower them back down with control.",
		videoUrl: "/videos/db_curl.mp4",
		imageUrl: "/images/db_curl.jpg",
	},
	{
		id: "bb_curl",
		name: "Barbell Curl",
		categoryId: "Arms",
		equipment: ["Barbell"],
		primaryMuscles: ["Biceps"],
		secondaryMuscles: ["forearms"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand holding a barbell at your thighs with palms facing forward. Curl the barbell up toward your shoulders, then lower it back down with control.",
		videoUrl: "/videos/bb_curl.mp4",
		imageUrl: "/images/bb_curl.jpg",
	},

	// Additional Chest Exercises
	{
		id: "incline_db_bench_press",
		name: "Incline Dumbbell Bench Press",
		categoryId: "Chest",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Upper Chest"],
		secondaryMuscles: ["Shoulders", "Triceps"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Set a bench to a 30-45 degree incline. Lie back holding dumbbells at shoulder level, press them up until arms are extended, then lower them back down with control.",
		videoUrl: "/videos/incline_db_bench_press.mp4",
		imageUrl: "/images/incline_db_bench_press.jpg",
	},
	{
		id: "incline_bb_bench_press",
		name: "Incline Barbell Bench Press",
		categoryId: "Chest",
		equipment: ["Barbell"],
		primaryMuscles: ["Upper Chest"],
		secondaryMuscles: ["Shoulders", "Triceps"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Set a bench to a 30-45 degree incline. Lie back gripping a barbell wider than shoulder width, lower it to your upper chest, then press back up to full extension.",
		videoUrl: "/videos/incline_bb_bench_press.mp4",
		imageUrl: "/images/incline_bb_bench_press.jpg",
	},
	{
		id: "decline_bb_bench_press",
		name: "Decline Barbell Bench Press",
		categoryId: "Chest",
		equipment: ["Barbell"],
		primaryMuscles: ["Lower Chest"],
		secondaryMuscles: ["Triceps"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Lie on a decline bench with feet secured, grip the barbell wider than shoulder width. Lower the bar to your lower chest, then press it back up to full extension.",
		videoUrl: "/videos/decline_bb_bench_press.mp4",
		imageUrl: "/images/decline_bb_bench_press.jpg",
	},
	{
		id: "chest_flys",
		name: "Dumbbell Chest Flys",
		categoryId: "Chest",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Chest"],
		secondaryMuscles: ["Shoulders"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Lie on a flat bench holding dumbbells directly above your chest with palms facing each other. Lower the weights in an arc motion until you feel a stretch in your chest, then bring them back up.",
		videoUrl: "/videos/chest_flys.mp4",
		imageUrl: "/images/chest_flys.jpg",
	},
	{
		id: "cable_flys",
		name: "Cable Flys",
		categoryId: "Chest",
		equipment: ["Cable"],
		primaryMuscles: ["Chest"],
		secondaryMuscles: ["Shoulders"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Stand in the center of a cable machine with cables set at chest height. With a slight forward lean, pull the handles in an arc motion in front of your chest, then return to the starting position with control.",
		videoUrl: "/videos/cable_flys.mp4",
		imageUrl: "/images/cable_flys.jpg",
	},
	{
		id: "push_ups",
		name: "Push-Ups",
		categoryId: "Chest",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Chest"],
		secondaryMuscles: ["Triceps", "Shoulders", "Core"],
		difficulty: "beginner",
		type: "bodyweight",
		instructions:
			"Start in a plank position with hands slightly wider than shoulder-width apart. Lower your body by bending your elbows until your chest nearly touches the floor, then push back up to the starting position.",
		videoUrl: "/videos/push_ups.mp4",
		imageUrl: "/images/push_ups.jpg",
	},

	// Additional Back Exercises
	{
		id: "lat_pulldown",
		name: "Lat Pulldown",
		categoryId: "Back",
		equipment: ["Cable", "Machine"],
		primaryMuscles: ["Lats"],
		secondaryMuscles: ["Biceps", "Shoulders"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Sit at a lat pulldown machine, grip the bar wider than shoulder width. Pull the bar down to your upper chest while squeezing your shoulder blades together, then slowly return to the starting position.",
		videoUrl: "/videos/lat_pulldown.mp4",
		imageUrl: "/images/lat_pulldown.jpg",
	},
	{
		id: "seated_cable_row",
		name: "Seated Cable Row",
		categoryId: "Back",
		equipment: ["Cable"],
		primaryMuscles: ["Mid Back"],
		secondaryMuscles: ["Biceps", "Lats"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Sit at a seated row machine with feet on the platform and knees slightly bent. Grab the handle, pull it towards your lower abdomen while keeping your back straight, then slowly return to the starting position.",
		videoUrl: "/videos/seated_cable_row.mp4",
		imageUrl: "/images/seated_cable_row.jpg",
	},
	{
		id: "bb_bent_over_row",
		name: "Barbell Bent-Over Row",
		categoryId: "Back",
		equipment: ["Barbell"],
		primaryMuscles: ["Mid Back"],
		secondaryMuscles: ["Lats", "Biceps", "Shoulders"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Bend at the hips with a slight knee bend, holding a barbell with an overhand grip. Pull the barbell to your lower chest while keeping your back flat, then lower it back down with control.",
		videoUrl: "/videos/bb_bent_over_row.mp4",
		imageUrl: "/images/bb_bent_over_row.jpg",
	},
	{
		id: "pull_ups",
		name: "Pull-Ups",
		categoryId: "Back",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Lats", "Upper Back"],
		secondaryMuscles: ["Biceps", "Shoulders"],
		difficulty: "advanced",
		type: "bodyweight",
		instructions:
			"Hang from a pull-up bar with hands slightly wider than shoulder width and palms facing away from you. Pull yourself up until your chin is over the bar, then lower back down with control.",
		videoUrl: "/videos/pull_ups.mp4",
		imageUrl: "/images/pull_ups.jpg",
	},
	{
		id: "chin_ups",
		name: "Chin-Ups",
		categoryId: "Back",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Lats", "Biceps"],
		secondaryMuscles: ["Upper Back", "Forearms"],
		difficulty: "advanced",
		type: "bodyweight",
		instructions:
			"Hang from a pull-up bar with hands shoulder-width apart and palms facing toward you. Pull yourself up until your chin is over the bar, then lower back down with control.",
		videoUrl: "/videos/chin_ups.mp4",
		imageUrl: "/images/chin_ups.jpg",
	},
	{
		id: "t_bar_row",
		name: "T-Bar Row",
		categoryId: "Back",
		equipment: ["Machine", "Barbell"],
		primaryMuscles: ["Mid Back"],
		secondaryMuscles: ["Lats", "Biceps"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Position yourself on a T-bar row machine with chest against the pad. Grip the handles, pull the weight toward your chest while keeping your back flat, then lower with control.",
		videoUrl: "/videos/t_bar_row.mp4",
		imageUrl: "/images/t_bar_row.jpg",
	},

	// Additional Leg Exercises
	{
		id: "bb_squat",
		name: "Barbell Squat",
		categoryId: "Legs",
		equipment: ["Barbell"],
		primaryMuscles: ["Quadriceps", "Glutes"],
		secondaryMuscles: ["Hamstrings", "Calves", "Core"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Position a barbell across your upper back, feet shoulder-width apart. Bend knees and hips to lower until thighs are parallel to the ground, then drive through heels to return to standing.",
		videoUrl: "/videos/bb_squat.mp4",
		imageUrl: "/images/bb_squat.jpg",
	},
	{
		id: "leg_press",
		name: "Leg Press",
		categoryId: "Legs",
		equipment: ["Machine"],
		primaryMuscles: ["Quadriceps", "Glutes"],
		secondaryMuscles: ["Hamstrings", "Calves"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Sit in a leg press machine with feet shoulder-width apart on the platform. Release the safety catches and lower the platform by bending your knees until they form 90-degree angles, then push back to the starting position.",
		videoUrl: "/videos/leg_press.mp4",
		imageUrl: "/images/leg_press.jpg",
	},
	{
		id: "lunges",
		name: "Dumbbell Lunges",
		categoryId: "Legs",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Quadriceps", "Glutes"],
		secondaryMuscles: ["Hamstrings", "Calves", "Core"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Hold dumbbells at your sides, take a step forward and lower your body until both knees form 90-degree angles. Push through the front heel to return to standing, then repeat with the other leg.",
		videoUrl: "/videos/lunges.mp4",
		imageUrl: "/images/lunges.jpg",
	},
	{
		id: "leg_extension",
		name: "Leg Extension",
		categoryId: "Legs",
		equipment: ["Machine"],
		primaryMuscles: ["Quadriceps"],
		secondaryMuscles: [],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Sit on a leg extension machine with feet under the pad. Extend your legs to lift the weight until your legs are straight, then slowly lower back to the starting position.",
		videoUrl: "/videos/leg_extension.mp4",
		imageUrl: "/images/leg_extension.jpg",
	},
	{
		id: "leg_curl",
		name: "Leg Curl",
		categoryId: "Legs",
		equipment: ["Machine"],
		primaryMuscles: ["Hamstrings"],
		secondaryMuscles: ["Calves"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Lie face down on a leg curl machine with heels under the pad. Curl your legs up by bending your knees and bringing your heels toward your buttocks, then slowly lower back down.",
		videoUrl: "/videos/leg_curl.mp4",
		imageUrl: "/images/leg_curl.jpg",
	},
	{
		id: "calf_raises",
		name: "Standing Calf Raises",
		categoryId: "Legs",
		equipment: ["Machine", "Bodyweight"],
		primaryMuscles: ["Calves"],
		secondaryMuscles: [],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand on a calf raise machine or elevated surface with the balls of your feet on the edge. Lower your heels below the platform, then raise up onto your toes as high as possible.",
		videoUrl: "/videos/calf_raises.mp4",
		imageUrl: "/images/calf_raises.jpg",
	},
	{
		id: "romanian_deadlift",
		name: "Romanian Deadlift",
		categoryId: "Legs",
		equipment: ["Barbell", "Dumbbell"],
		primaryMuscles: ["Hamstrings", "Glutes"],
		secondaryMuscles: ["Lower Back", "Forearms"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Start standing with a barbell at hip level. Hinge at your hips and lower the bar while keeping your back straight and knees slightly bent. Lower until you feel a stretch in your hamstrings, then return to standing.",
		videoUrl: "/videos/romanian_deadlift.mp4",
		imageUrl: "/images/romanian_deadlift.jpg",
	},

	// Additional Shoulder Exercises
	{
		id: "overhead_press",
		name: "Barbell Overhead Press",
		categoryId: "Shoulders",
		equipment: ["Barbell"],
		primaryMuscles: ["Shoulders"],
		secondaryMuscles: ["Triceps", "Upper Chest"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Stand with feet shoulder-width apart holding a barbell at shoulder height. Press the barbell overhead until your arms are fully extended, then lower it back to shoulder level.",
		videoUrl: "/videos/overhead_press.mp4",
		imageUrl: "/images/overhead_press.jpg",
	},
	{
		id: "db_shoulder_press",
		name: "Dumbbell Shoulder Press",
		categoryId: "Shoulders",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Shoulders"],
		secondaryMuscles: ["Triceps", "Upper Chest"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Sit or stand holding dumbbells at shoulder height with palms facing forward. Press the weights overhead until arms are extended, then lower them back to shoulder level.",
		videoUrl: "/videos/db_shoulder_press.mp4",
		imageUrl: "/images/db_shoulder_press.jpg",
	},
	{
		id: "lateral_raise",
		name: "Lateral Raise",
		categoryId: "Shoulders",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Shoulders"],
		secondaryMuscles: ["Upper Traps"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand holding dumbbells at your sides. With a slight bend in your elbows, raise the weights out to your sides until they reach shoulder level, then lower them back down with control.",
		videoUrl: "/videos/lateral_raise.mp4",
		imageUrl: "/images/lateral_raise.jpg",
	},
	{
		id: "front_raise",
		name: "Front Raise",
		categoryId: "Shoulders",
		equipment: ["Dumbbell", "Barbell"],
		primaryMuscles: ["Front Deltoids"],
		secondaryMuscles: ["Upper Chest"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand holding dumbbells in front of your thighs. With palms facing down and a slight bend in your elbows, raise the weights in front of you to shoulder height, then lower back down.",
		videoUrl: "/videos/front_raise.mp4",
		imageUrl: "/images/front_raise.jpg",
	},
	{
		id: "rear_delt_flys",
		name: "Rear Delt Flys",
		categoryId: "Shoulders",
		equipment: ["Dumbbell", "Cable"],
		primaryMuscles: ["Rear Deltoids"],
		secondaryMuscles: ["Middle Traps", "Rhomboids"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Bend forward at the hips holding dumbbells with palms facing each other. Raise the weights out to your sides while keeping elbows slightly bent, then lower back down with control.",
		videoUrl: "/videos/rear_delt_flys.mp4",
		imageUrl: "/images/rear_delt_flys.jpg",
	},
	{
		id: "upright_row",
		name: "Upright Row",
		categoryId: "Shoulders",
		equipment: ["Barbell", "Dumbbell", "Cable"],
		primaryMuscles: ["Shoulders", "Traps"],
		secondaryMuscles: ["Biceps"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Stand holding a barbell in front of your thighs with an overhand grip. Pull the bar straight up toward your chin, leading with your elbows, then lower it back down with control.",
		videoUrl: "/videos/upright_row.mp4",
		imageUrl: "/images/upright_row.jpg",
	},

	// Additional Arm Exercises
	{
		id: "tricep_pushdown",
		name: "Tricep Pushdown",
		categoryId: "Arms",
		equipment: ["Cable"],
		primaryMuscles: ["Triceps"],
		secondaryMuscles: [],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand facing a cable machine with a straight or V-bar attachment at chest height. Keeping your elbows close to your sides, push the bar down until your arms are fully extended, then return to the starting position.",
		videoUrl: "/videos/tricep_pushdown.mp4",
		imageUrl: "/images/tricep_pushdown.jpg",
	},
	{
		id: "tricep_extension",
		name: "Overhead Tricep Extension",
		categoryId: "Arms",
		equipment: ["Dumbbell", "Cable"],
		primaryMuscles: ["Triceps"],
		secondaryMuscles: [],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand or sit holding a dumbbell with both hands overhead. Lower the weight behind your head by bending your elbows, then extend your arms back up to the starting position.",
		videoUrl: "/videos/tricep_extension.mp4",
		imageUrl: "/images/tricep_extension.jpg",
	},
	{
		id: "skullcrushers",
		name: "Skullcrushers",
		categoryId: "Arms",
		equipment: ["Barbell", "Dumbbell"],
		primaryMuscles: ["Triceps"],
		secondaryMuscles: ["Forearms"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Lie on a bench holding a barbell or dumbbells with arms extended above your chest. Bend your elbows to lower the weight toward your forehead, then extend your arms to return to the starting position.",
		videoUrl: "/videos/skullcrushers.mp4",
		imageUrl: "/images/skullcrushers.jpg",
	},
	{
		id: "concentration_curl",
		name: "Concentration Curl",
		categoryId: "Arms",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Biceps"],
		secondaryMuscles: ["Forearms"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Sit on a bench with legs spread, holding a dumbbell in one hand. Rest your elbow against your inner thigh, curl the weight toward your shoulder, then lower it back down with control.",
		videoUrl: "/videos/concentration_curl.mp4",
		imageUrl: "/images/concentration_curl.jpg",
	},
	{
		id: "hammer_curl",
		name: "Hammer Curl",
		categoryId: "Arms",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Biceps", "Brachialis"],
		secondaryMuscles: ["Forearms"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand holding dumbbells at your sides with palms facing your body. Curl the weights toward your shoulders while maintaining the neutral grip, then lower them back down with control.",
		videoUrl: "/videos/hammer_curl.mp4",
		imageUrl: "/images/hammer_curl.jpg",
	},
	{
		id: "preacher_curl",
		name: "Preacher Curl",
		categoryId: "Arms",
		equipment: ["Barbell", "Dumbbell", "Machine"],
		primaryMuscles: ["Biceps"],
		secondaryMuscles: ["Forearms"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Sit at a preacher bench with arms resting on the pad, holding a barbell with an underhand grip. Curl the weight toward your shoulders, then lower it back down with control.",
		videoUrl: "/videos/preacher_curl.mp4",
		imageUrl: "/images/preacher_curl.jpg",
	},
	{
		id: "tricep_dips",
		name: "Tricep Dips",
		categoryId: "Arms",
		equipment: ["Bodyweight", "Machine"],
		primaryMuscles: ["Triceps"],
		secondaryMuscles: ["Chest", "Shoulders"],
		difficulty: "intermediate",
		type: "bodyweight",
		instructions:
			"Support yourself on parallel bars with arms extended. Lower your body by bending your elbows until your upper arms are parallel to the ground, then push back up to the starting position.",
		videoUrl: "/videos/tricep_dips.mp4",
		imageUrl: "/images/tricep_dips.jpg",
	},

	// Additional Core Exercises
	{
		id: "crunches",
		name: "Crunches",
		categoryId: "Core",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Rectus Abdominis"],
		secondaryMuscles: ["Obliques"],
		difficulty: "beginner",
		type: "bodyweight",
		instructions:
			"Lie on your back with knees bent and feet flat on the floor. Place hands behind your head or across your chest, then lift your shoulders off the ground by contracting your abs. Lower back down with control.",
		videoUrl: "/videos/crunches.mp4",
		imageUrl: "/images/crunches.jpg",
	},
	{
		id: "leg_raises",
		name: "Lying Leg Raises",
		categoryId: "Core",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Lower Abs"],
		secondaryMuscles: ["Hip Flexors"],
		difficulty: "intermediate",
		type: "bodyweight",
		instructions:
			"Lie on your back with legs straight and hands under your lower back for support. Raise your legs toward the ceiling until they're perpendicular to the floor, then lower them back down without touching the ground.",
		videoUrl: "/videos/leg_raises.mp4",
		imageUrl: "/images/leg_raises.jpg",
	},
	{
		id: "planks",
		name: "Planks",
		categoryId: "Core",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Core"],
		secondaryMuscles: ["Shoulders", "Glutes"],
		difficulty: "beginner",
		type: "bodyweight",
		instructions:
			"Start in a push-up position, then lower onto your forearms with elbows under shoulders. Keep your body in a straight line from head to heels, engaging your core muscles. Hold the position for the desired time.",
		videoUrl: "/videos/planks.mp4",
		imageUrl: "/images/planks.jpg",
	},
	{
		id: "russian_twist",
		name: "Russian Twist",
		categoryId: "Core",
		equipment: ["Bodyweight", "Dumbbell"],
		primaryMuscles: ["Obliques"],
		secondaryMuscles: ["Rectus Abdominis"],
		difficulty: "intermediate",
		type: "bodyweight",
		instructions:
			"Sit on the floor with knees bent and feet lifted slightly off the ground. Lean back slightly, keeping your back straight. Twist your torso from side to side, touching the ground on each side if possible.",
		videoUrl: "/videos/russian_twist.mp4",
		imageUrl: "/images/russian_twist.jpg",
	},
	{
		id: "mountain_climbers",
		name: "Mountain Climbers",
		categoryId: "Core",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Core"],
		secondaryMuscles: ["Shoulders", "Chest", "Hip Flexors"],
		difficulty: "beginner",
		type: "bodyweight",
		instructions:
			"Start in a plank position with arms extended. Bring one knee toward your chest, then quickly switch legs in a running motion, keeping your hips low and core engaged throughout the movement.",
		videoUrl: "/videos/mountain_climbers.mp4",
		imageUrl: "/images/mountain_climbers.jpg",
	},
	{
		id: "bicycle_crunches",
		name: "Bicycle Crunches",
		categoryId: "Core",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Rectus Abdominis", "Obliques"],
		secondaryMuscles: ["Hip Flexors"],
		difficulty: "beginner",
		type: "bodyweight",
		instructions:
			"Lie on your back with hands behind your head and knees bent. Lift shoulders off the ground and bring one knee toward your chest while rotating to touch it with the opposite elbow. Alternate sides in a pedaling motion.",
		videoUrl: "/videos/bicycle_crunches.mp4",
		imageUrl: "/images/bicycle_crunches.jpg",
	},
	{
		id: "hanging_leg_raise",
		name: "Hanging Leg Raise",
		categoryId: "Core",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Lower Abs"],
		secondaryMuscles: ["Hip Flexors", "Forearms"],
		difficulty: "advanced",
		type: "bodyweight",
		instructions:
			"Hang from a pull-up bar with an overhand grip. Keep your body still as you raise your legs until they're parallel to the ground or higher, then lower them back down with control.",
		videoUrl: "/videos/hanging_leg_raise.mp4",
		imageUrl: "/images/hanging_leg_raise.jpg",
	},

	// Additional Compound Exercises
	{
		id: "clean_and_jerk",
		name: "Clean and Jerk",
		categoryId: "Shoulders",
		equipment: ["Barbell"],
		primaryMuscles: ["Shoulders", "Legs", "Back"],
		secondaryMuscles: ["Core", "Traps", "Arms"],
		difficulty: "advanced",
		type: "weightlifting",
		instructions:
			"Start with a barbell on the floor. In one fluid motion, pull the bar up while dropping under it to catch it at shoulder height. Then, dip slightly and explosively press the bar overhead while splitting your legs. Return to standing with the weight overhead.",
		videoUrl: "/videos/clean_and_jerk.mp4",
		imageUrl: "/images/clean_and_jerk.jpg",
	},
	{
		id: "power_clean",
		name: "Power Clean",
		categoryId: "Back",
		equipment: ["Barbell"],
		primaryMuscles: ["Back", "Shoulders", "Legs"],
		secondaryMuscles: ["Core", "Arms"],
		difficulty: "advanced",
		type: "weightlifting",
		instructions:
			"Start with a barbell on the floor. In one explosive movement, pull the bar from the floor to your shoulders, dropping slightly to catch it in a quarter squat position. Stand up straight to complete the lift.",
		videoUrl: "/videos/power_clean.mp4",
		imageUrl: "/images/power_clean.jpg",
	},
	{
		id: "front_squat",
		name: "Front Squat",
		categoryId: "Legs",
		equipment: ["Barbell"],
		primaryMuscles: ["Quadriceps", "Glutes"],
		secondaryMuscles: ["Core", "Upper Back"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Hold a barbell across your front delts with elbows high. Squat down until thighs are parallel to the ground or lower, keeping chest up and elbows high, then stand back up.",
		videoUrl: "/videos/front_squat.mp4",
		imageUrl: "/images/front_squat.jpg",
	},
	{
		id: "kettlebell_swing",
		name: "Kettlebell Swing",
		categoryId: "Back",
		equipment: ["Other"],
		primaryMuscles: ["Hamstrings", "Glutes", "Lower Back"],
		secondaryMuscles: ["Shoulders", "Core"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Stand with feet shoulder-width apart holding a kettlebell with both hands. Hinge at the hips to swing the kettlebell between your legs, then thrust your hips forward to swing the weight up to chest height.",
		videoUrl: "/videos/kettlebell_swing.mp4",
		imageUrl: "/images/kettlebell_swing.jpg",
	},
	{
		id: "box_jumps",
		name: "Box Jumps",
		categoryId: "Legs",
		equipment: ["Other"],
		primaryMuscles: ["Quadriceps", "Glutes", "Calves"],
		secondaryMuscles: ["Hamstrings", "Core"],
		difficulty: "intermediate",
		type: "bodyweight",
		instructions:
			"Stand in front of a sturdy box or platform. Lower into a quarter squat, then explosively jump onto the box, landing with soft knees. Step back down and repeat.",
		videoUrl: "/videos/box_jumps.mp4",
		imageUrl: "/images/box_jumps.jpg",
	},
	{
		id: "burpees",
		name: "Burpees",
		categoryId: "Cardio",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Full Body"],
		secondaryMuscles: [],
		difficulty: "intermediate",
		type: "cardio-time",
		instructions:
			"Start standing, then squat down and place hands on the floor. Jump feet back into a plank position, perform a push-up, jump feet back to hands, then explosively jump up with arms overhead.",
		videoUrl: "/videos/burpees.mp4",
		imageUrl: "/images/burpees.jpg",
	},
	{
		id: "battle_ropes",
		name: "Battle Ropes",
		categoryId: "Cardio",
		equipment: ["Other"],
		primaryMuscles: ["Shoulders", "Arms", "Core"],
		secondaryMuscles: ["Back"],
		difficulty: "intermediate",
		type: "cardio-time",
		instructions:
			"Stand with feet shoulder-width apart, holding one rope end in each hand. Create waves in the ropes by alternately raising and lowering each arm, or by moving both arms together.",
		videoUrl: "/videos/battle_ropes.mp4",
		imageUrl: "/images/battle_ropes.jpg",
	},

	// Additional Chest Exercises
	{
		id: "decline_push_ups",
		name: "Decline Push-Ups",
		categoryId: "Chest",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Lower Chest"],
		secondaryMuscles: ["Triceps", "Shoulders", "Core"],
		difficulty: "intermediate",
		type: "bodyweight",
		instructions:
			"Place your feet on an elevated surface like a bench and hands on the floor in push-up position. Lower your chest toward the floor, then push back up to the starting position.",
		videoUrl: "/videos/decline_push_ups.mp4",
		imageUrl: "/images/decline_push_ups.jpg",
	},
	{
		id: "incline_push_ups",
		name: "Incline Push-Ups",
		categoryId: "Chest",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Upper Chest"],
		secondaryMuscles: ["Triceps", "Shoulders"],
		difficulty: "beginner",
		type: "bodyweight",
		instructions:
			"Place your hands on an elevated surface like a bench and feet on the floor in push-up position. Lower your chest toward the bench, then push back up to the starting position.",
		videoUrl: "/videos/incline_push_ups.mp4",
		imageUrl: "/images/incline_push_ups.jpg",
	},
	{
		id: "pec_deck",
		name: "Pec Deck Machine",
		categoryId: "Chest",
		equipment: ["Machine"],
		primaryMuscles: ["Chest"],
		secondaryMuscles: ["Shoulders"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Sit in the pec deck machine with your back against the pad. Place your forearms against the vertical pads. Push the pads together in front of you by squeezing your chest muscles, then slowly return to the starting position.",
		videoUrl: "/videos/pec_deck.mp4",
		imageUrl: "/images/pec_deck.jpg",
	},
	{
		id: "svend_press",
		name: "Svend Press",
		categoryId: "Chest",
		equipment: ["Other"],
		primaryMuscles: ["Chest"],
		secondaryMuscles: ["Shoulders", "Triceps"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Press a weight plate between your palms at chest level. Extend your arms forward while keeping the plate pressed between your hands, then bring it back to your chest.",
		videoUrl: "/videos/svend_press.mp4",
		imageUrl: "/images/svend_press.jpg",
	},

	// Additional Back Exercises
	{
		id: "meadows_row",
		name: "Meadows Row",
		categoryId: "Back",
		equipment: ["Barbell"],
		primaryMuscles: ["Lats", "Upper Back"],
		secondaryMuscles: ["Biceps", "Forearms"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Place one end of a barbell in a corner or landmine attachment. Stand perpendicular to the bar, grab the weighted end with one hand, and pull it toward your hip while keeping your back straight.",
		videoUrl: "/videos/meadows_row.mp4",
		imageUrl: "/images/meadows_row.jpg",
	},
	{
		id: "straight_arm_pulldown",
		name: "Straight Arm Pulldown",
		categoryId: "Back",
		equipment: ["Cable"],
		primaryMuscles: ["Lats"],
		secondaryMuscles: ["Chest", "Triceps"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand facing a high cable pulley with a straight bar attachment. Grab the bar with arms extended, then pull it down toward your thighs while keeping your arms straight. Slowly return to the starting position.",
		videoUrl: "/videos/straight_arm_pulldown.mp4",
		imageUrl: "/images/straight_arm_pulldown.jpg",
	},
	{
		id: "face_pull",
		name: "Face Pull",
		categoryId: "Back",
		equipment: ["Cable"],
		primaryMuscles: ["Rear Deltoids", "Traps"],
		secondaryMuscles: ["Rotator Cuff"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Attach a rope to a cable pulley at upper chest height. Grab the ends and step back. Pull the rope toward your face with elbows high, separating the ends as you pull. Return to the starting position with control.",
		videoUrl: "/videos/face_pull.mp4",
		imageUrl: "/images/face_pull.jpg",
	},
	{
		id: "inverted_row",
		name: "Inverted Row",
		categoryId: "Back",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Upper Back"],
		secondaryMuscles: ["Biceps", "Forearms"],
		difficulty: "beginner",
		type: "bodyweight",
		instructions:
			"Set a bar in a rack or Smith machine at waist height. Lie underneath with your heels on the ground and grab the bar with hands wider than shoulder-width. Pull your chest up to the bar, then lower yourself back down with control.",
		videoUrl: "/videos/inverted_row.mp4",
		imageUrl: "/images/inverted_row.jpg",
	},

	// Additional Shoulder Exercises
	{
		id: "arnold_press",
		name: "Arnold Press",
		categoryId: "Shoulders",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Shoulders"],
		secondaryMuscles: ["Triceps"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Sit with dumbbells at shoulder height, palms facing you. As you press up, rotate your palms to face forward at the top. Reverse the movement on the way down.",
		videoUrl: "/videos/arnold_press.mp4",
		imageUrl: "/images/arnold_press.jpg",
	},
	{
		id: "landmine_press",
		name: "Landmine Press",
		categoryId: "Shoulders",
		equipment: ["Barbell"],
		primaryMuscles: ["Shoulders"],
		secondaryMuscles: ["Triceps", "Core"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Place one end of a barbell in a landmine attachment or corner. Grip the other end with one or both hands at shoulder height, then press it up and away from your body. Lower it back to shoulder height with control.",
		videoUrl: "/videos/landmine_press.mp4",
		imageUrl: "/images/landmine_press.jpg",
	},
	{
		id: "cable_y_raise",
		name: "Cable Y Raise",
		categoryId: "Shoulders",
		equipment: ["Cable"],
		primaryMuscles: ["Front Deltoids", "Traps"],
		secondaryMuscles: ["Upper Back"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Stand facing away from a low cable pulley with a handle in each hand. Raise your arms up and out to form a Y shape above your head, then lower them back down with control.",
		videoUrl: "/videos/cable_y_raise.mp4",
		imageUrl: "/images/cable_y_raise.jpg",
	},

	// Additional Arm Exercises
	{
		id: "db_kickbacks",
		name: "Dumbbell Kickbacks",
		categoryId: "Arms",
		equipment: ["Dumbbell"],
		primaryMuscles: ["Triceps"],
		secondaryMuscles: [],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Bend forward with one hand on a bench for support. Hold a dumbbell in your other hand with upper arm parallel to the floor. Extend your arm backward until it's straight, then return to the starting position.",
		videoUrl: "/videos/db_kickbacks.mp4",
		imageUrl: "/images/db_kickbacks.jpg",
	},
	{
		id: "close_grip_bench",
		name: "Close Grip Bench Press",
		categoryId: "Arms",
		equipment: ["Barbell"],
		primaryMuscles: ["Triceps"],
		secondaryMuscles: ["Chest", "Shoulders"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Lie on a bench holding a barbell with hands about shoulder-width apart. Lower the bar to your lower chest, then press it back up to full extension.",
		videoUrl: "/videos/close_grip_bench.mp4",
		imageUrl: "/images/close_grip_bench.jpg",
	},
	{
		id: "ez_bar_curl",
		name: "EZ Bar Curl",
		categoryId: "Arms",
		equipment: ["Barbell"],
		primaryMuscles: ["Biceps"],
		secondaryMuscles: ["Forearms"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Stand holding an EZ bar with an underhand grip at hip level. Curl the bar up toward your shoulders, then lower it back down with control.",
		videoUrl: "/videos/ez_bar_curl.mp4",
		imageUrl: "/images/ez_bar_curl.jpg",
	},
	{
		id: "wrist_curl",
		name: "Wrist Curl",
		categoryId: "Arms",
		equipment: ["Dumbbell", "Barbell"],
		primaryMuscles: ["Forearms"],
		secondaryMuscles: [],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Sit on a bench with forearms resting on your thighs and wrists extending beyond your knees. Hold a weight with palms up, lower it by bending your wrists, then curl it back up.",
		videoUrl: "/videos/wrist_curl.mp4",
		imageUrl: "/images/wrist_curl.jpg",
	},
	{
		id: "reverse_wrist_curl",
		name: "Reverse Wrist Curl",
		categoryId: "Arms",
		equipment: ["Dumbbell", "Barbell"],
		primaryMuscles: ["Forearms"],
		secondaryMuscles: [],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Sit on a bench with forearms resting on your thighs and wrists extending beyond your knees. Hold a weight with palms down, lower it by bending your wrists, then curl it back up.",
		videoUrl: "/videos/reverse_wrist_curl.mp4",
		imageUrl: "/images/reverse_wrist_curl.jpg",
	},

	// Additional Leg Exercises
	{
		id: "bulgarian_split_squat",
		name: "Bulgarian Split Squat",
		categoryId: "Legs",
		equipment: ["Bodyweight", "Dumbbell"],
		primaryMuscles: ["Quadriceps", "Glutes"],
		secondaryMuscles: ["Hamstrings", "Calves", "Core"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Stand with one foot in front of you and the other behind you on a bench. Lower your back knee toward the floor by bending your front leg, then push back up to the starting position.",
		videoUrl: "/videos/bulgarian_split_squat.mp4",
		imageUrl: "/images/bulgarian_split_squat.jpg",
	},
	{
		id: "glute_bridge",
		name: "Glute Bridge",
		categoryId: "Legs",
		equipment: ["Bodyweight", "Barbell"],
		primaryMuscles: ["Glutes"],
		secondaryMuscles: ["Hamstrings", "Lower Back"],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Lie on your back with knees bent and feet flat on the floor. Push through your heels to lift your hips toward the ceiling, squeezing your glutes at the top. Lower back down with control.",
		videoUrl: "/videos/glute_bridge.mp4",
		imageUrl: "/images/glute_bridge.jpg",
	},
	{
		id: "hip_thrust",
		name: "Hip Thrust",
		categoryId: "Legs",
		equipment: ["Barbell"],
		primaryMuscles: ["Glutes"],
		secondaryMuscles: ["Hamstrings"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Sit with your upper back against a bench and a barbell across your hips. Plant your feet on the ground, then drive through your heels to lift your hips toward the ceiling. Lower back down with control.",
		videoUrl: "/videos/hip_thrust.mp4",
		imageUrl: "/images/hip_thrust.jpg",
	},
	{
		id: "sissy_squat",
		name: "Sissy Squat",
		categoryId: "Legs",
		equipment: ["Bodyweight", "Machine"],
		primaryMuscles: ["Quadriceps"],
		secondaryMuscles: ["Calves"],
		difficulty: "advanced",
		type: "bodyweight",
		instructions:
			"Hold onto a support with one hand. Lean back with straight arms and rise onto your toes. Bend your knees to lower your body while keeping your torso and thighs aligned. Return to the starting position.",
		videoUrl: "/videos/sissy_squat.mp4",
		imageUrl: "/images/sissy_squat.jpg",
	},
	{
		id: "good_morning",
		name: "Good Morning",
		categoryId: "Legs",
		equipment: ["Barbell"],
		primaryMuscles: ["Hamstrings", "Lower Back"],
		secondaryMuscles: ["Glutes"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Stand with a barbell across your upper back. Hinge at the hips to bend forward with a slight knee bend, keeping your back straight. Return to the starting position by extending your hips.",
		videoUrl: "/videos/good_morning.mp4",
		imageUrl: "/images/good_morning.jpg",
	},
	{
		id: "seated_calf_raise",
		name: "Seated Calf Raise",
		categoryId: "Legs",
		equipment: ["Machine"],
		primaryMuscles: ["Calves"],
		secondaryMuscles: [],
		difficulty: "beginner",
		type: "weightlifting",
		instructions:
			"Sit at a calf raise machine with the pads on your lower thighs and balls of your feet on the platform. Lower your heels as far as possible, then raise them as high as possible by extending your ankles.",
		videoUrl: "/videos/seated_calf_raise.mp4",
		imageUrl: "/images/seated_calf_raise.jpg",
	},

	// Additional Core Exercises
	{
		id: "ab_wheel_rollout",
		name: "Ab Wheel Rollout",
		categoryId: "Core",
		equipment: ["Other"],
		primaryMuscles: ["Rectus Abdominis"],
		secondaryMuscles: ["Shoulders", "Lats", "Hip Flexors"],
		difficulty: "advanced",
		type: "bodyweight",
		instructions:
			"Kneel on the floor holding an ab wheel with both hands. Roll the wheel forward, extending your body as far as possible while keeping your core tight. Pull back to the starting position using your core muscles.",
		videoUrl: "/videos/ab_wheel_rollout.mp4",
		imageUrl: "/images/ab_wheel_rollout.jpg",
	},
	{
		id: "dragon_flag",
		name: "Dragon Flag",
		categoryId: "Core",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Core"],
		secondaryMuscles: ["Lower Back", "Hip Flexors"],
		difficulty: "advanced",
		type: "bodyweight",
		instructions:
			"Lie on a bench holding the edge behind your head. Raise your legs and lower back off the bench, keeping your body straight. Lower your body back down slowly, maintaining a straight line from shoulders to feet.",
		videoUrl: "/videos/dragon_flag.mp4",
		imageUrl: "/images/dragon_flag.jpg",
	},
	{
		id: "hollow_hold",
		name: "Hollow Hold",
		categoryId: "Core",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Core"],
		secondaryMuscles: ["Hip Flexors"],
		difficulty: "intermediate",
		type: "bodyweight",
		instructions:
			"Lie on your back and press your lower back into the floor. Extend your arms overhead and raise your legs off the ground. Hold this position while keeping your lower back in contact with the floor.",
		videoUrl: "/videos/hollow_hold.mp4",
		imageUrl: "/images/hollow_hold.jpg",
	},
	{
		id: "side_plank",
		name: "Side Plank",
		categoryId: "Core",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Obliques"],
		secondaryMuscles: ["Shoulders", "Glutes"],
		difficulty: "intermediate",
		type: "bodyweight",
		instructions:
			"Lie on your side with legs straight and prop yourself up on your elbow with your forearm flat on the floor. Raise your hips so your body forms a straight line from head to feet, and hold this position.",
		videoUrl: "/videos/side_plank.mp4",
		imageUrl: "/images/side_plank.jpg",
	},
	{
		id: "cable_woodchoppers",
		name: "Cable Woodchoppers",
		categoryId: "Core",
		equipment: ["Cable"],
		primaryMuscles: ["Obliques"],
		secondaryMuscles: ["Shoulders", "Hips"],
		difficulty: "intermediate",
		type: "weightlifting",
		instructions:
			"Stand sideways to a cable machine with the pulley set high. Grab the handle with both hands, then pull it down and across your body in a chopping motion. Return to the starting position with control.",
		videoUrl: "/videos/cable_woodchoppers.mp4",
		imageUrl: "/images/cable_woodchoppers.jpg",
	},

	// Additional Cardio Exercises
	{
		id: "assault_bike",
		name: "Assault Bike",
		categoryId: "Cardio",
		equipment: ["Cardio Equipment"],
		primaryMuscles: ["Full Body"],
		secondaryMuscles: [],
		difficulty: "scalable",
		type: "cardio-distance",
		instructions:
			"Sit on the assault bike with feet on the pedals and hands on the handles. Push with your legs while simultaneously pulling and pushing the handles in a coordinated motion.",
		videoUrl: "/videos/assault_bike.mp4",
		imageUrl: "/images/assault_bike.jpg",
	},
	{
		id: "sled_push",
		name: "Sled Push",
		categoryId: "Cardio",
		equipment: ["Other"],
		primaryMuscles: ["Legs", "Shoulders", "Core"],
		secondaryMuscles: ["Chest", "Triceps"],
		difficulty: "intermediate",
		type: "cardio-distance",
		instructions:
			"Stand behind a weighted sled with hands on the handles and arms extended. Lean forward with a straight back and drive the sled forward by pushing with your legs.",
		videoUrl: "/videos/sled_push.mp4",
		imageUrl: "/images/sled_push.jpg",
	},
	{
		id: "farmer_carry",
		name: "Farmer's Carry",
		categoryId: "Cardio",
		equipment: ["Dumbbell", "Other"],
		primaryMuscles: ["Forearms", "Traps", "Core"],
		secondaryMuscles: ["Shoulders", "Legs"],
		difficulty: "intermediate",
		type: "cardio-distance",
		instructions:
			"Hold a heavy weight in each hand with arms at your sides. Maintain good posture with shoulders back and core engaged as you walk for the designated distance or time.",
		videoUrl: "/videos/farmer_carry.mp4",
		imageUrl: "/images/farmer_carry.jpg",
	},
	{
		id: "hill_sprints",
		name: "Hill Sprints",
		categoryId: "Cardio",
		equipment: ["Bodyweight"],
		primaryMuscles: ["Quadriceps", "Hamstrings", "Calves"],
		secondaryMuscles: ["Glutes", "Core"],
		difficulty: "advanced",
		type: "cardio-distance",
		instructions:
			"Find a moderate to steep hill. Sprint up the hill as fast as possible, focusing on driving your knees high and pumping your arms. Walk back down to recover, then repeat.",
		videoUrl: "/videos/hill_sprints.mp4",
		imageUrl: "/images/hill_sprints.jpg",
	},
];

// Helper function to get exercises by category
export function getExercisesByCategory(categoryId) {
	return exercises.filter((exercise) => exercise.categoryId === categoryId);
}

// Helper function to get exercises by equipment
export function getExercisesByEquipment(equipmentId) {
	return exercises.filter((exercise) =>
		exercise.equipment.includes(equipmentId)
	);
}

// Helper function to get exercises by difficulty
export function getExercisesByDifficulty(difficultyLevel) {
	return exercises.filter(
		(exercise) => exercise.difficulty === difficultyLevel
	);
}

// Example usage:
// const chestExercises = getExercisesByCategory("chest");
// const dumbbellExercises = getExercisesByEquipment("dumbbell");
// const beginnerExercises = getExercisesByDifficulty("beginner");
